server:
  port: 8081

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.35.183.75:3306/ai_resume?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: ai@resume0415
    hikari:
      minimum-idle: 5           # 最小空闲连接数
      maximum-pool-size: 20     #最大连接数（默认10）
      idle-timeout: 600000      # 空闲连接超时时间（毫秒）
      connection-timeout: 30000 # 连接超时时间（毫秒，默认30000）
      max-lifetime: 1800000     # 连接最大存活时间（毫秒）
      pool-name: Hikari-resume  # 连接池名称
      auto-commit: true         # 自动提交
  data:
    redis:
      host: 101.35.183.75
      port: 6379
      database: 6
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
      password: ai@resume0415
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
sa-token:
  # Token 名称（同时也是 Cookie 名称）
  token-name: satoken
  # Token 有效期（单位：秒），默认30天，-1 代表永久有效
  timeout: 2592000
  # 是否允许同一账号多地同时登录（true=允许，false=新登录挤掉旧登录）
  is-concurrent: true
  # Token 风格，推荐 uuid 或 random-128
  token-style: uuid
  # 是否在控制台打印 Sa-Token 的 ASCII 艺术字版本号
  is-print: true

mybatis-plus:
  configuration:
    # 自动驼峰命名
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置Mapper映射文件
  mapper-locations: classpath*:com/ai/resume/mapper/xml/*.xml

knife4j:
  enable: true

minio:
  endpoint: http://101.35.183.75:9000
  access-key: root
  secret-key: ai@resume0415
  bucket-name: resume

algo:
  thread:
    core-pool-size: 10
    max-pool-size: 50
    queue-capacity: 100
    keep-alive-seconds: 120
    thread-name-prefix: algo-analysis-
    complete-shutdown: true
    await-termination-seconds: 120
  path:
    main-path: python main.py
    ranking-path: python main.py