CREATE TABLE `resume` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '简历ID',
  `user_id` bigint NOT NULL COMMENT '所属用户ID',
  `file_name` varchar(50) NOT NULL COMMENT '文件名称',
  `file_size` bigint NOT NULL COMMENT '文件大小',
  `file_type` varchar(20) NOT NULL COMMENT '文件类型',
  `file_url` varchar(255) NOT NULL COMMENT '文件地址',
  `description` varchar(200) DEFAULT NULL COMMENT '个人描述',
  `parse_status` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '解析状态：0待解析 1解析中 2成功 3失败',
  `parse_error_msg` varchar(500) DEFAULT NULL COMMENT '解析失败原因',
  `full_name` varchar(100) DEFAULT NULL COMMENT '姓名',
  `gender` tinyint unsigned DEFAULT NULL COMMENT '性别：0未知 1男 2女',
  `birthday` date DEFAULT NULL COMMENT '出生日期',
  `phone` varchar(20) DEFAULT NULL COMMENT '手机号',
  `email` varchar(100) DEFAULT NULL COMMENT '邮箱',
  `nationality` varchar(50) DEFAULT NULL COMMENT '国籍',
  `location` varchar(100) DEFAULT NULL COMMENT '所在城市',
  `summary` text COMMENT '简历内容',
  `total_work_years` decimal(3,1) DEFAULT NULL COMMENT '总工作年限（年）',
  `expected_salary` varchar(50) DEFAULT NULL COMMENT '期望薪资（如：20-30k·15薪）',
  `job_status` tinyint unsigned DEFAULT NULL COMMENT '求职状态：0在职考虑 1离职 2应届等',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '是否删除：0未删 1已删',
  PRIMARY KEY (`id`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='简历表';